---
AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - "*/node_modules/**/*"
    - "*/vendor/**/*"
require:
  - rubocop-gemfile
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-rake
