---
AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Performance/UnfreezeString:
  Enabled: false
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
