require_relative "parser/boolean"
require_relative "parser/code"
require_relative "parser/name"
require_relative "parser/nothing"
require_relative "parser/number"
require_relative "parser/string"
require_relative "parser/statement"
require_relative "parser/call"
